# Generated by Django 4.2.2 on 2023-06-28 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_bleak', '0002_blescanevent_create_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blescanevent',
            name='scan_mode',
            field=models.CharField(choices=[('seq', 'Sequential'), ('itv', 'Interval')], default='itv', help_text='scan mode', max_length=3, verbose_name='scan mode'),
        ),
    ]
