@startuml "django-bleak-sequencial"
participant device
participant ble_scanner
database db

loop while BleScanEvent.is_enabled
    device -> ble_scanner: advertising
    activate ble_scanner #CA2B13
    device -x ble_scanner: advertising
    alt matches BleScanFilter
        ble_scanner -> db: save BleScanDevice
        ble_scanner -> db: save BleScanResult
    deactivate ble_scanner
    end
    deactivate ble_scanner
end
@enduml
